"""Static entity descriptions shared across drivers."""

from __future__ import annotations

from typing import TypeVar

from .models import BinarySensorDescription, MeasurementDescription

BASE_SENSOR_DESCRIPTIONS: tuple[MeasurementDescription, ...] = (
    MeasurementDescription(
        key="collector_remote_ip",
        name="Collector IP",
        icon="mdi:ip-network",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="configured_collector_ip",
        name="Configured Collector IP",
        icon="mdi:crosshairs-gps",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_pn",
        name="Collector PN",
        icon="mdi:access-point-network",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_profile",
        name="Collector Profile",
        icon="mdi:card-bulleted-settings-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_profile_key",
        name="Collector Profile Key",
        icon="mdi:key-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_heartbeat_devcode",
        name="Collector Heartbeat Devcode",
        icon="mdi:heart-pulse",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_heartbeat_payload",
        name="Collector Heartbeat Payload",
        icon="mdi:hexadecimal",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_heartbeat_age_seconds",
        name="Collector Heartbeat Age",
        unit="s",
        icon="mdi:timer-sand",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_heartbeat_ascii",
        name="Collector Heartbeat ASCII",
        icon="mdi:alphabetical-variant",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_heartbeat_payload_len",
        name="Collector Heartbeat Length",
        icon="mdi:numeric",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_heartbeat_format",
        name="Collector Heartbeat Format",
        icon="mdi:shape-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_heartbeat_suffix",
        name="Collector Heartbeat Suffix",
        icon="mdi:form-textbox",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_heartbeat_suffix_kind",
        name="Collector Heartbeat Suffix Kind",
        icon="mdi:text-box-check-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_heartbeat_suffix_uint",
        name="Collector Heartbeat Suffix Value",
        icon="mdi:numeric",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_devcode_major",
        name="Collector Devcode Major",
        icon="mdi:numeric-1-box-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_devcode_minor",
        name="Collector Devcode Minor",
        icon="mdi:numeric-2-box-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_pn_prefix",
        name="Collector PN Prefix",
        icon="mdi:format-letter-case",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_pn_digits",
        name="Collector PN Digits",
        icon="mdi:numeric",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_devcode",
        name="Collector Devcode",
        icon="mdi:chip",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_udp_reply",
        name="Collector UDP Reply",
        icon="mdi:message-reply-text-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_udp_reply_from",
        name="Collector UDP Reply From",
        icon="mdi:arrow-decision-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="driver_key",
        name="Driver",
        icon="mdi:puzzle-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="protocol_family",
        name="Protocol Family",
        icon="mdi:transit-connection-variant",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="variant_key",
        name="Protocol Variant",
        icon="mdi:source-branch",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="profile_name",
        name="Effective Profile",
        icon="mdi:file-document-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="register_schema_name",
        name="Effective Register Schema",
        icon="mdi:file-tree-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="model_name",
        name="Model",
        icon="mdi:information-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="serial_number",
        name="Serial Number",
        icon="mdi:identifier",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="detection_confidence",
        name="Detection Confidence",
        icon="mdi:check-decagram-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="control_mode",
        name="Control Mode",
        icon="mdi:tune-variant",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="controls_enabled",
        name="Controls Enabled",
        icon="mdi:toggle-switch-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="control_policy_reason",
        name="Control Policy Reason",
        icon="mdi:shield-lock-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="control_policy_summary",
        name="Control Policy Summary",
        icon="mdi:shield-check-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="write_capabilities",
        name="Write Capabilities",
        icon="mdi:pencil-box-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="blocked_write_capabilities",
        name="Blocked Write Capabilities",
        icon="mdi:pencil-off-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="blocked_write_count",
        name="Blocked Write Count",
        icon="mdi:counter",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="blocked_write_summary",
        name="Blocked Write Summary",
        icon="mdi:format-list-bulleted-square",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="last_error",
        name="Last Error",
        icon="mdi:alert-circle-outline",
        diagnostic=True,
        enabled_default=True,
        live=False,
    ),
    MeasurementDescription(
        key="runtime_recovery_streak",
        name="Runtime Recovery Streak",
        icon="mdi:counter",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="runtime_reconnect_count",
        name="Runtime Reconnect Count",
        icon="mdi:restart",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="runtime_backoff_seconds",
        name="Runtime Backoff",
        unit="s",
        icon="mdi:timer-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="runtime_last_success_age_seconds",
        name="Runtime Last Success Age",
        unit="s",
        icon="mdi:timeline-clock-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="runtime_last_recovery_reason",
        name="Runtime Last Recovery Reason",
        icon="mdi:stethoscope",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="support_bundle_path",
        name="Support Bundle Path",
        icon="mdi:archive-arrow-down-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="support_package_path",
        name="Support Archive Path",
        icon="mdi:package-variant-closed",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="support_package_download_path",
        name="Support Archive Download Path",
        icon="mdi:file-link-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="support_package_download_url",
        name="Support Archive Download URL",
        icon="mdi:download-network-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="support_package_download_relative_url",
        name="Support Archive Download Relative URL",
        icon="mdi:link-variant",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="local_profile_draft_path",
        name="Local Profile Draft Path",
        icon="mdi:file-document-edit-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="local_schema_draft_path",
        name="Local Schema Draft Path",
        icon="mdi:file-tree-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="local_metadata_status",
        name="Local Metadata Status",
        icon="mdi:test-tube",
        diagnostic=True,
        enabled_default=True,
        live=False,
    ),
)

BASE_BINARY_SENSOR_DESCRIPTIONS: tuple[BinarySensorDescription, ...] = ()


_DescriptionT = TypeVar("_DescriptionT")


def merge_descriptions(
    *groups: tuple[_DescriptionT, ...],
) -> tuple[_DescriptionT, ...]:
    """Merge groups and preserve the first description for each key."""

    merged: dict[str, _DescriptionT] = {}
    for group in groups:
        for description in group:
            merged.setdefault(getattr(description, "key"), description)
    return tuple(merged.values())
