"""Static entity descriptions shared across drivers."""

from __future__ import annotations

from typing import TypeVar

from .models import BinarySensorDescription, MeasurementDescription

BASE_SENSOR_DESCRIPTIONS: tuple[MeasurementDescription, ...] = (
    MeasurementDescription(
        key="collector_remote_ip",
        name="Collector IP",
        icon="mdi:ip-network",
        diagnostic=False,
        live=False,
    ),
    MeasurementDescription(
        key="configured_collector_ip",
        name="Configured Collector IP",
        icon="mdi:crosshairs-gps",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_pn",
        name="Collector PN",
        icon="mdi:access-point-network",
        diagnostic=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_profile",
        name="Collector Profile",
        icon="mdi:card-bulleted-settings-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_profile_key",
        name="Collector Profile Key",
        icon="mdi:key-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_heartbeat_devcode",
        name="Collector Heartbeat Devcode",
        icon="mdi:heart-pulse",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_heartbeat_payload",
        name="Collector Heartbeat Payload",
        icon="mdi:hexadecimal",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_heartbeat_age_seconds",
        name="Collector Heartbeat Age",
        unit="s",
        icon="mdi:timer-sand",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_heartbeat_ascii",
        name="Collector Heartbeat ASCII",
        icon="mdi:alphabetical-variant",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_heartbeat_payload_len",
        name="Collector Heartbeat Length",
        icon="mdi:numeric",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_heartbeat_format",
        name="Collector Heartbeat Format",
        icon="mdi:shape-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_heartbeat_suffix",
        name="Collector Heartbeat Suffix",
        icon="mdi:form-textbox",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_heartbeat_suffix_kind",
        name="Collector Heartbeat Suffix Kind",
        icon="mdi:text-box-check-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_heartbeat_suffix_uint",
        name="Collector Heartbeat Suffix Value",
        icon="mdi:numeric",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_devcode_major",
        name="Collector Devcode Major",
        icon="mdi:numeric-1-box-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_devcode_minor",
        name="Collector Devcode Minor",
        icon="mdi:numeric-2-box-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_pn_prefix",
        name="Collector PN Prefix",
        icon="mdi:format-letter-case",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_pn_digits",
        name="Collector PN Digits",
        icon="mdi:numeric",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_devcode",
        name="Collector Devcode",
        icon="mdi:chip",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_udp_reply",
        name="Collector UDP Reply",
        icon="mdi:message-reply-text-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_udp_reply_from",
        name="Collector UDP Reply From",
        icon="mdi:arrow-decision-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="smartess_collector_version",
        name="Collector Firmware Version",
        icon="mdi:chip",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_protocol_version",
        name="Collector Protocol Version",
        icon="mdi:source-branch",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_hardware_version",
        name="Collector Hardware Version",
        icon="mdi:memory",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_local_ip_address",
        name="Collector Local IP",
        icon="mdi:lan-connect",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_server_endpoint",
        name="Collector Server Endpoint",
        icon="mdi:cloud-outline",
        diagnostic=False,
        enabled_default=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_listener_status",
        name="Collector Listener Status",
        icon="mdi:lan-check",
        diagnostic=True,
        enabled_default=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_poll_utilization_percent",
        name="Poll Utilization",
        unit="%",
        icon="mdi:gauge",
        diagnostic=True,
        state_class="measurement",
        enabled_default=True,
        live=False,
        suggested_display_precision=0,
    ),
    MeasurementDescription(
        key="collector_poll_mode",
        name="Poll Mode",
        translation_key="collector_poll_mode",
        device_class="enum",
        options=("auto", "manual"),
        icon="mdi:timer-cog",
        diagnostic=True,
        enabled_default=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_poll_context",
        name="Poll Context",
        translation_key="collector_poll_context",
        device_class="enum",
        options=("runtime", "detection", "collector"),
        icon="mdi:timeline-question-outline",
        diagnostic=True,
        enabled_default=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_poll_phase_breakdown",
        name="Poll Phase Breakdown",
        translation_key="collector_poll_phase_breakdown",
        icon="mdi:chart-timeline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="runtime_refresh_phase_breakdown",
        name="Refresh Phase Breakdown",
        translation_key="runtime_refresh_phase_breakdown",
        icon="mdi:chart-gantt",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="driver_slow_requests",
        name="Slowest Driver Requests",
        translation_key="driver_slow_requests",
        icon="mdi:speedometer-slow",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="runtime_driver_state",
        name="Runtime Driver State",
        translation_key="runtime_driver_state",
        device_class="enum",
        options=("driver_bound", "driver_unbound", "collector_offline"),
        icon="mdi:connection",
        diagnostic=True,
        enabled_default=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_poll_current_interval_seconds",
        name="Current Poll Interval",
        unit="s",
        icon="mdi:timer-play-outline",
        diagnostic=True,
        state_class="measurement",
        enabled_default=True,
        live=False,
        suggested_display_precision=0,
    ),
    MeasurementDescription(
        key="collector_poll_next_interval_seconds",
        name="Next Poll Interval",
        unit="s",
        icon="mdi:timer-refresh-outline",
        diagnostic=True,
        state_class="measurement",
        enabled_default=False,
        live=False,
        suggested_display_precision=0,
    ),
    MeasurementDescription(
        key="collector_poll_manual_interval_seconds",
        name="Manual Poll Interval",
        unit="s",
        icon="mdi:timer-edit-outline",
        diagnostic=True,
        state_class="measurement",
        enabled_default=False,
        live=False,
        suggested_display_precision=0,
    ),
    MeasurementDescription(
        key="collector_poll_duration_ms",
        name="Poll Duration",
        unit="ms",
        icon="mdi:timer-outline",
        diagnostic=True,
        state_class="measurement",
        enabled_default=True,
        live=False,
        suggested_display_precision=0,
    ),
    MeasurementDescription(
        key="collector_poll_duration_avg_ms",
        name="Average Poll Duration",
        unit="ms",
        icon="mdi:timer-sync-outline",
        diagnostic=True,
        state_class="measurement",
        enabled_default=False,
        live=False,
        suggested_display_precision=0,
    ),
    MeasurementDescription(
        key="collector_poll_duration_max_ms",
        name="Maximum Poll Duration",
        unit="ms",
        icon="mdi:timer-alert-outline",
        diagnostic=True,
        state_class="measurement",
        enabled_default=False,
        live=False,
        suggested_display_precision=0,
    ),
    MeasurementDescription(
        key="collector_poll_recommended_min_interval_seconds",
        name="Recommended Poll Interval",
        unit="s",
        icon="mdi:timer-cog-outline",
        diagnostic=True,
        state_class="measurement",
        enabled_default=True,
        live=False,
        suggested_display_precision=0,
    ),
    MeasurementDescription(
        key="collector_poll_detection_retry_interval_seconds",
        name="Detection Retry Interval",
        unit="s",
        icon="mdi:timer-sand",
        diagnostic=True,
        state_class="measurement",
        enabled_default=False,
        live=False,
        suggested_display_precision=0,
    ),
    MeasurementDescription(
        key="collector_poll_overrun_streak",
        name="Poll Overrun Streak",
        icon="mdi:counter",
        diagnostic=True,
        state_class="measurement",
        enabled_default=False,
        live=False,
        suggested_display_precision=0,
    ),
    MeasurementDescription(
        key="collector_poll_high_utilization_streak",
        name="Poll High Utilization Streak",
        icon="mdi:counter",
        diagnostic=True,
        state_class="measurement",
        enabled_default=False,
        live=False,
        suggested_display_precision=0,
    ),
    MeasurementDescription(
        key="collector_callback_identity_status",
        name="Collector Callback Identity",
        icon="mdi:identifier",
        diagnostic=True,
        enabled_default=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_callback_identity_summary",
        name="Collector Callback Identity Summary",
        icon="mdi:text-box-search-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_listener_bind_host",
        name="Collector Listener Bind Host",
        icon="mdi:server-network",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_listener_bind_endpoint",
        name="Collector Listener Bind Endpoint",
        icon="mdi:server-network",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_listener_effective_host",
        name="Collector Listener Effective Host",
        icon="mdi:ip-network-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_listener_advertised_endpoint",
        name="Collector Listener Advertised Endpoint",
        icon="mdi:bullhorn-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_listener_rebind_count",
        name="Collector Listener Rebind Count",
        icon="mdi:counter",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_listener_last_error",
        name="Collector Listener Last Error",
        icon="mdi:alert-circle-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_cloud_family",
        name="Collector Cloud Family",
        icon="mdi:cloud-braces",
        diagnostic=True,
        enabled_default=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_cloud_family_source",
        name="Collector Cloud Family Source",
        icon="mdi:chart-timeline-variant",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_cloud_family_confidence",
        name="Collector Cloud Family Confidence",
        icon="mdi:shield-check-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_type",
        name="Collector Type",
        icon="mdi:router-wireless",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_reboot_required",
        name="Collector Reboot Required",
        icon="mdi:restart-alert",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_transmission_mode",
        name="Collector Transmission Mode",
        icon="mdi:transit-connection-variant",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_serial_baudrate",
        name="Collector Serial Baudrate",
        icon="mdi:serial-port",
        diagnostic=True,
        enabled_default=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_ssid",
        name="Connected Wi-Fi SSID",
        icon="mdi:wifi",
        diagnostic=False,
        enabled_default=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_network_diagnostics",
        name="Collector Network Diagnostics",
        icon="mdi:lan-pending",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_signal_strength",
        name="Collector Signal Strength",
        unit="dBm",
        device_class="signal_strength",
        state_class="measurement",
        diagnostic=True,
        enabled_default=True,
        live=False,
        suggested_display_precision=0,
    ),
    MeasurementDescription(
        key="collector_signal_strength_raw",
        name="Collector Signal Strength Raw",
        icon="mdi:signal-distance-variant",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_signal_strength_source",
        name="Collector Signal Source",
        icon="mdi:wifi-marker",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_signal_quality",
        name="Collector Signal Quality",
        translation_key="collector_signal_quality",
        device_class="enum",
        options=("unknown", "excellent", "good", "fair", "weak"),
        icon="mdi:signal-cellular-2",
        diagnostic=False,
        enabled_default=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_upload_mode",
        name="Collector Upload Mode",
        icon="mdi:upload-network-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_system_time",
        name="Collector System Time",
        icon="mdi:clock-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_cloud_heartbeat_value",
        name="Collector Cloud Heartbeat Value",
        icon="mdi:heart-pulse",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_link_status",
        name="Collector Link Status",
        icon="mdi:lan-check",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_wifi_scan_list",
        name="Collector Wi-Fi Scan List",
        icon="mdi:wifi-cog",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_bridge_version",
        name="Collector Bridge Version",
        icon="mdi:bridge",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_operation_mode",
        name="Collector Operation Mode",
        translation_key="collector_operation_mode",
        device_class="enum",
        options=(
            "smartess_cloud_home_assistant",
            "home_assistant_only",
        ),
        icon="mdi:transit-connection-variant",
        diagnostic=False,
        enabled_default=True,
        live=False,
    ),
    MeasurementDescription(
        key="collector_operation_endpoint_sync_error",
        name="Collector Callback Sync Error",
        icon="mdi:alert-circle-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="collector_onboarding_status",
        name="Collector Onboarding",
        icon="mdi:clipboard-check-outline",
        diagnostic=True,
        enabled_default=True,
        live=False,
    ),
    MeasurementDescription(
        key="smartess_protocol_raw_id",
        name="Collector Protocol Raw ID",
        icon="mdi:identifier",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="smartess_protocol_asset_id",
        name="Collector Protocol Asset ID",
        icon="mdi:identifier",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="smartess_protocol_asset_name",
        name="Collector Protocol Asset",
        icon="mdi:file-document-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="smartess_protocol_suffix",
        name="Collector Protocol Suffix",
        icon="mdi:form-textbox",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="smartess_protocol_profile_key",
        name="Collector Protocol Profile Key",
        icon="mdi:key-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="smartess_protocol_name",
        name="Collector Protocol Name",
        icon="mdi:label-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="smartess_device_address",
        name="Collector Device Address",
        icon="mdi:numeric",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="driver_key",
        name="Driver",
        icon="mdi:puzzle-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="protocol_family",
        name="Protocol Family",
        icon="mdi:transit-connection-variant",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="variant_key",
        name="Protocol Variant",
        icon="mdi:source-branch",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="profile_name",
        name="Effective Profile",
        icon="mdi:file-document-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="register_schema_name",
        name="Effective Register Schema",
        icon="mdi:file-tree-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="model_name",
        name="Model",
        icon="mdi:information-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="serial_number",
        name="Serial Number",
        icon="mdi:identifier",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="detection_confidence",
        name="Detection Confidence",
        icon="mdi:check-decagram-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="controls_enabled",
        name="Controls Enabled",
        icon="mdi:toggle-switch-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="control_policy_reason",
        name="Control Policy Reason",
        icon="mdi:shield-lock-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="control_policy_summary",
        name="Control Policy Summary",
        icon="mdi:shield-check-outline",
        diagnostic=True,
        live=False,
    ),
    MeasurementDescription(
        key="write_capabilities",
        name="Write Capabilities",
        icon="mdi:pencil-box-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="blocked_write_capabilities",
        name="Blocked Write Capabilities",
        icon="mdi:pencil-off-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="blocked_write_count",
        name="Blocked Write Count",
        icon="mdi:counter",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="blocked_write_summary",
        name="Blocked Write Summary",
        icon="mdi:format-list-bulleted-square",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="last_error",
        name="Last Error",
        icon="mdi:alert-circle-outline",
        diagnostic=True,
        enabled_default=True,
        live=False,
    ),
    MeasurementDescription(
        key="runtime_recovery_streak",
        name="Runtime Recovery Streak",
        icon="mdi:counter",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="runtime_reconnect_count",
        name="Runtime Reconnect Count",
        icon="mdi:restart",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="runtime_backoff_seconds",
        name="Runtime Backoff",
        unit="s",
        icon="mdi:timer-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="runtime_last_success_age_seconds",
        name="Runtime Last Success Age",
        unit="s",
        icon="mdi:timeline-clock-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="runtime_last_recovery_reason",
        name="Runtime Last Recovery Reason",
        icon="mdi:stethoscope",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="support_bundle_path",
        name="Support Bundle Path",
        icon="mdi:archive-arrow-down-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="support_package_path",
        name="Support Archive Path",
        icon="mdi:package-variant-closed",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="support_package_download_path",
        name="Support Archive Download Path",
        icon="mdi:file-link-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="support_package_download_url",
        name="Support Archive Download URL",
        icon="mdi:download-network-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="support_package_download_relative_url",
        name="Support Archive Download Relative URL",
        icon="mdi:link-variant",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="local_profile_draft_path",
        name="Local Profile Draft Path",
        icon="mdi:file-document-edit-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="local_schema_draft_path",
        name="Local Schema Draft Path",
        icon="mdi:file-tree-outline",
        diagnostic=True,
        enabled_default=False,
        live=False,
    ),
    MeasurementDescription(
        key="local_metadata_status",
        name="Local Metadata Status",
        icon="mdi:test-tube",
        diagnostic=True,
        enabled_default=True,
        live=False,
    ),
)

BASE_BINARY_SENSOR_DESCRIPTIONS: tuple[BinarySensorDescription, ...] = ()


_DescriptionT = TypeVar("_DescriptionT")


def merge_descriptions(
    *groups: tuple[_DescriptionT, ...],
) -> tuple[_DescriptionT, ...]:
    """Merge groups and preserve the first description for each key."""

    merged: dict[str, _DescriptionT] = {}
    for group in groups:
        for description in group:
            merged.setdefault(getattr(description, "key"), description)
    return tuple(merged.values())
